services:
  - type: worker
    name: redpanda
    region: singapore
    plan: free
    runtime: docker
    dockerfilePath: ./redpanda/Dockerfile.redpanda

  - type: web
    name: order-service
    region: singapore
    plan: free
    runtime: docker
    dockerfilePath: ./services/order-service/Dockerfile.order
    envVars:
      - key: KAFKA_BROKER
        value: redpanda:9092

  - type: worker
    name: location-service
    region: singapore
    plan: free
    runtime: docker
    dockerfilePath: ./services/location-service/Dockerfile.location
    envVars:
      - key: KAFKA_BROKER
        value: redpanda:9092

  - type: worker
    name: notification-service
    region: singapore
    plan: free
    runtime: docker
    dockerfilePath: ./services/notification-service/Dockerfile.notification
    envVars:
      - key: KAFKA_BROKER
        value: redpanda:9092